version: '3.7'
services:
  api:
    build: .
    restart: always
    networks:
       - api
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: mongo:3.6-xenial 
    restart: always
    networks:
       - api

networks:
  api: