version: '3.7'
services:
  api:
    build: .
    restart: always
    networks:
       - overlay
    ports:
      - "3000:3000"
    depends_on: 
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
       - overlay
    ports: 
      - "27019:27017"

networks:
  overlay: